services:
  postgres:
      image: postgres:latest
      container_name: postgres_evcs_management
      environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_HOST_AUTH_METHOD: trust
      ports:
          - "5432:5432"
      volumes:
          - pg_data:/var/lib/postgresql/data # Persistent data storage
          - ./database/postgresdb.sql:/docker-entrypoint-initdb.d/init.sql
      networks:
          - evcs_network

